### ISSUE TITLE
Uploading a fake release of Tethys made by some randoms to rat

### ISSUE THREAD

**Issue by pvpb0t** [3000IQPlay/Old-Tethys-leaked#5]

**Comment by 3000IQPlay** [comment]
It was getting updates... Thats weird

**Comment by 3000IQPlay** [comment]
Since the last Gugu leak 2.3.0 they added AutoDupe

**Comment by 3000IQPlay** [comment]
Bruh what? it was made by Popbobik otw Lunar, VirtualBox and some other ppl
